name = "glum"
version = "0.0.1"

target = "javascript"

description = "NativeScript Gleam Game Engine Library"
repository = { type = "github", user = "ethanthoma", repo = "glum" }
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_community_colour = ">= 2.0.1 and < 3.0.0"
given = ">= 5.0.4 and < 6.0.0"
javascript_mutable_reference = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
